### PR TITLE
[MIG] nubosoft: Initial migration of files from V14 to 15.0 t58555

### PR DESCRIPTION
**Pull request by desdelinux**

### CODE REVIEW

**Comment by desdelinux** [comment]
@angelesgl17 @hugho-ad @luisg123v done

**Review by luisg123v — CHANGES_REQUESTED** [review]
The `mexico` repo is 99 commits outdated. Could you update changes, please?

**Comment by desdelinux** [comment]
> The `mexico` repo is 99 commits outdated. Could you update changes, please?

done

**Review by luisg123v — APPROVED** [review]
LGTM :+1:

**Pull request merged**
